version: '3.8'

services:
  # PHP Application
  web:
    build: .
    container_name: civic_sense_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads
    environment:
      - DB_HOST=mysql
      - DB_NAME=civic_sense_db
      - DB_USER=civic_user
      - DB_PASS=civic_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - civic_network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: civic_sense_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: civic_sense_db
      MYSQL_USER: civic_user
      MYSQL_PASSWORD: civic_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - civic_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "civic_user", "-pcivic_password"]
      timeout: 20s
      retries: 10

  # phpMyAdmin (Optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: civic_sense_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: civic_user
      PMA_PASSWORD: civic_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - civic_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  civic_network:
    driver: bridge
