[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_sqlite", "sqlite"]

[phases.install]
cmds = ["mkdir -p database"]

[phases.build]
cmds = ["echo 'PHP app built successfully'"]

[start]
cmd = "php -S 0.0.0.0:$PORT"
